[project]
name = "pynetnetworkautomation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black==23.3.0",
    "emoji==2.2.0",
    "ipython==8.6.0",
    "netmiko==4.2.0",
    "pylama==8.4.1",
    "rich==13.3.3",
]
